apiVersion: v1
kind: Service
metadata:
  name: k8
spec:
  selector:
    app: k8
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8
spec:
  replicas: 6
  selector:
    matchLabels:
      app: k8
  template:
    metadata:
      labels:
        app: k8
    spec:
      containers:
        - name: app
          image: jverneaut/k8:8daaa8e939d9dce1e19259c76122ea84e53e26c0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
