apiVersion: v1
kind: Service
metadata:
  name: k8
spec:
  selector:
    app: k8
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8
  template:
    metadata:
      labels:
        app: k8
    spec:
      containers:
        - name: app
          image: jverneaut/k8:f5ce995cf2e2c7f675f072f14589b45bd6854d1b
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://redis:6379
          imagePullPolicy: Always
