apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
      initContainers:
        - name: disable-thp
          image: redis:4.0-alpine
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
          command: ['sh', '-c', 'echo never > /host-sys/kernel/mm/transparent_hugepage/enabled']
      containers:
        - name: redis
          image: redis:4.0-alpine
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 350m
              memory: 1024Mi
          ports:
            - containerPort: 6379
